version: '3.8'
services:
  mysql-db:
    image: mysql:8.1
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  java-app:
    build: .
    depends_on:
      - mysql-db

volumes:
  mysql-data:
